Refactor ship placement
totine/OStatki pull request #10
Opened 2018-07-09 13:31 UTC by totine

- Fleet is generic now
- Ship is an interface now that is implemented by UndirectedShip, DirectedShip and PlacedShip
- Move ship placing from Board to dedicated class (ShipPlacer)
- Board API contains only isMastPlaceable() and placeMast() now

2018-07-09 13:43 UTC, boczkas commented on src/main/java/placement/controller/RandomFleetPlacer.java
>              while (!ship.isPlaced()) {
extract method

2018-07-09 13:45 UTC, boczkas commented on src/main/java/placement/controller/RandomFleetPlacer.java
> +                DirectedShip ship2 = ship.direct(direction);
directedShip

2018-07-09 14:03 UTC, boczkas commented on src/main/java/placement/controller/RandomFleetPlacer.java
> +                ship = ShipPlacer.placeShip(board, ship2, randomCoordinates);
if(ShipPlacer.placeShipOnBoard(board, directedShip, randomCoordinates) == ShipPlacement.SUCCESSFUL){
  ship = new PlacedShip(ship, randomCoordinates);
}

2018-07-09 14:08 UTC, boczkas commented on src/main/java/placement/controller/RandomFleetPlacer.java
>          int index = random.nextInt(directions.length - 1);
magic number

2018-07-09 14:14 UTC, boczkas commented on src/main/java/placement/controller/ShipPlacer.java
> +    static Ship placeShip(Board board, DirectedShip ship, Coordinates headCoordinates) {
will be changed - no review

2018-07-09 14:15 UTC, boczkas commented on src/main/java/placement/controller/ShipPlacer.java
> +    public static Ship placeShip(Board board, DirectedShip ship1, int x, int y) {
ship1 - where is ship2?

2018-07-09 14:18 UTC, boczkas commented on src/main/java/placement/controller/ShipPlacer.java
> +    public static Ship placeShip(Board board, DirectedShip ship1, int x, int y) {
self comment:
coordinates created only for testing purposes - should be refactored

2018-07-09 14:19 UTC, boczkas commented on src/main/java/placement/model/Fleet.java
> +        ShipType[] shipTypes = {BATTLESHIP,
Who are those?

2018-07-09 14:20 UTC, boczkas commented on src/main/java/placement/model/board/Board.java
> +    public boolean isEmpty() {
self comment:
used only in tests

2018-07-09 14:21 UTC, boczkas commented on src/main/java/placement/model/board/Board.java
> +    public FieldState getFieldState(int x, int y) {
self comment:
used only in tests

2018-07-09 14:25 UTC, boczkas commented on src/main/java/placement/model/board/Board.java
> +        neighbours.remove(coordinates);
self comment:
coordinates - coordinatesToSurrounded with buffer

2018-07-09 14:26 UTC, boczkas commented on src/main/java/placement/model/ship/DirectedShip.java
> +
/n to be removed

2018-07-09 14:27 UTC, boczkas commented on src/main/java/placement/model/ship/DirectedShip.java
> +        this.mastNumber = mastCount;
both of them are the same, you can have same name

2018-07-09 14:29 UTC, boczkas commented on src/main/java/placement/model/ship/DirectedShip.java
> +            Coordinates nextCoord = direction.nextCoordinates();
Coordinates nextCoord initialization before while

2018-07-09 14:30 UTC, boczkas commented on src/main/java/placement/model/ship/PlacedShip.java
> +    private final String id;
remove it

2018-07-09 14:31 UTC, boczkas commented on src/main/java/placement/model/ship/UndirectedShip.java
> +
/n remove

2018-07-09 14:34 UTC, boczkas commented on src/test/java/placement/model/ShipPlacerTests.java
> +
/n remove

2018-07-09 14:36 UTC, boczkas commented on src/test/java/placement/model/ShipPlacerTests.java
> +package placement.model;
try to extract magic numbers

2018-07-09 14:38 UTC, boczkas commented on src/test/java/placement/model/ShipPlacerTests.java
> +        DirectedShip ship1 = new DirectedShip(3, Direction.EAST);
ship1 - shipDirectedEast
ship2 - shipDirectedSouth

2018-07-09 14:43 UTC, boczkas requested changes
Cosmetics

2018-07-09 16:03 UTC, boczkas commented on src/main/java/placement/model/board/Board.java
> +    private Set<Coordinates> getNeighboursToMarkAsBuffer(Coordinates coordinatesToSurrounded) {
self comment:
name to be changed

2018-07-09 16:04 UTC, boczkas approved these changes
:+1:

2018-07-09 16:33 UTC, KrzysztofDzioba commented on src/main/java/placement/controller/RandomFleetPlacer.java
> +    Fleet<PlacedShip> placeFleet() {
What about getPlacedFleet?

2018-07-09 16:39 UTC, KrzysztofDzioba commented on src/main/java/placement/controller/ShipPlacer.java
> +    public static boolean tryToPlaceShip(Board board, DirectedShip ship, Coordinates headCoordinates) {
javadoc?

2018-07-09 16:40 UTC, KrzysztofDzioba commented on src/main/java/placement/controller/FleetController.java
> +    public static Fleet<PlacedShip> generatePlacedStandardFleet() {
javadoc?

2018-07-09 16:41 UTC, KrzysztofDzioba commented on src/main/java/placement/model/Fleet.java
> +    public static Fleet<UndirectedShip> createDefaultFleet() {
javadoc?

2018-07-09 16:49 UTC, KrzysztofDzioba commented on src/main/java/placement/model/board/Board.java
> +                        coordinatesToSurrounded.getX() + i,
You have already a method to add coordinates to each other (in Coordinates class)

2018-07-09 16:49 UTC, KrzysztofDzioba commented on src/main/java/placement/model/board/Board.java
>          for (int i = -1; i <= 1; i++) {
What about extracting it to a new method?

2018-07-09 16:50 UTC, KrzysztofDzioba commented on src/main/java/placement/model/board/Board.java
>          for (int i = -1; i <= 1; i++) {
You can change "i" for "row"

2018-07-09 16:50 UTC, KrzysztofDzioba commented on src/main/java/placement/model/board/Board.java
>              for (int j = -1; j <= 1; j++) {
and "j" for "col"

2018-07-09 16:54 UTC, KrzysztofDzioba commented on src/main/java/placement/view/FleetFromRandomGenerator.java
>      public final GUIFleet getFleet() {
what about getGUIFleet?

2018-07-09 16:56 UTC, KrzysztofDzioba commented on src/main/java/placement/view/GUIShip.java
>      private List<Coordinates> structure;
structure -> coordinates

2018-07-09 17:00 UTC, KrzysztofDzioba requested changes
Small fixes needed

2018-07-10 07:34 UTC, KrzysztofDzioba approved these changes

2018-07-10 07:35 UTC, merged