Gui server connection
totine/OStatki pull request #20
Opened 2018-07-17 13:22 UTC by AdrianHarenczyk

This pull request makes changes to various files. Overall it adds simple Client -> Server communication. Example has elements of GUI which will not be included in final version as text field some buttons and text area. These elements helped to test connection between server and client application. Added script run_both.sh helps with running both server and client app, it was tested on two machines. It works on Ubuntu Linux for certain with gnome-terminal. You can use it to start the app.

2018-07-17 13:53 UTC, krzysieksr commented on client/src/main/java/connection/ClientIO.java
> +            out.println("Domyślna");
WTF?

2018-07-17 13:56 UTC, krzysieksr commented on client/src/main/java/connection/GUIServerConnection.java
> +        e.printStackTrace();
Please add some external logger mechanism in the future.

2018-07-17 14:05 UTC, krzysieksr commented on shared/src/main/java/placement/model/field/BufferField.java
>          return "⚓";
You could change anchor to another sign

2018-07-17 14:06 UTC, krzysieksr approved these changes

2018-07-18 09:11 UTC, agaped requested changes
please correct

2018-07-18 09:11 UTC, agaped commented on shared/src/main/java/placement/model/Coordinates.java
> +   public final int getX() {
missing javadoc

2018-07-18 09:26 UTC, agaped approved these changes
:+1:

2018-07-18 09:28 UTC, merged